name: meshtastic_bridge
description: Bridges radios via BLE

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  universal_ble: ^0.21.1
  permission_handler: ^12.0.0
  protobuf: ^4.0.0
  fixnum: ^1.1.1
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
